CREATE TABLE Person1 (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fullname varchar(100) NOT NULL UNIQUE,
                        birhdate int NOT NULL
);

CREATE TABLE Book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      prodyear int NOT NULL,
                      user_id int REFERENCES Person1(id) ON DELETE SET NULL
);